version: "3.9"

services:
  # Service untuk aplikasi Node.js
  jgateway:
    build: .
    container_name: jgateway-app
    ports:
      - "3100:3000"
    env_file:
      - .env
    depends_on:
      - mariadb
      - redis               
    restart: unless-stopped
    volumes:
      - ./:/app
      - ./uploads:/app/uploads

  # Service untuk database MariaDB
  mariadb:
    image: mariadb:11
    container_name: jgateway-db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: db_jiget
      MYSQL_USER: jiget_user
      MYSQL_PASSWORD: jiget_pass
    volumes:
      - db_data:/var/lib/mysql
    restart: unless-stopped

  # Service untuk Redis
  redis:
    image: redis:7-alpine
    container_name: jgateway-redis
    restart: unless-stopped
    ports:
      - "6379:6379"          
    volumes:
      - redis_data:/data     

volumes:
  db_data:
  redis_data:
